---
apiVersion: v1
kind: Namespace
metadata:
    name: nginx-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webapp
  namespace: nginx-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webapp
  template:
    metadata:
      labels:
        app: nginx-webapp
    spec:
      containers:
      - name: nginx-webapp
        image: howieowi/nginx_ocbc_lab:${VERSION}
        resources:
          requests:
            memory: "250Mi"
            cpu: "0.5"
          limits:
            memory: "500Mi"
            cpu: "1"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-webapp
  namespace: nginx-webapp
  labels:
    app: nginx-webapp
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: 10Mbps
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: nginx-webapp